### ISSUE TITLE
[US2] Form 

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone-project#3]
## Value proposition

As a user
I want to specify my workout plan's details
in order to use the app as intended

## Description

![image](https://github.com/doctype-Melvin/capstone-project/assets/71100019/e8d77cd5-4acb-4ce2-b0e1-7b272b2bd4db)

## Acceptance criteria

- [ ] there's a button to save name and days of users workout plans
- [ ] clicking save forwards users to a summary page of their plans
- [ ] the workout days are listed and contain a button that says 'add exercise'
- [ ] clicking the 'add exercise' button opens a form 
- [ ] this form allows users to enter exercise name, sets, reps and weight

## Tasks

- [ ] create feature/plan-form branch
- [ ] create button to save name and days of workout plan
- [ ] create WorkoutDay component
- [ ] this component shows the day for which it will store data
- [ ] write the logic to toggle the view from 'name and days' form to 'plan summary page'
- [ ] the component has a button that says 'add exercise'
- [ ] clicking the 'add exercise' button adds a form to the WorkoutDay component
- [ ] within that form there should be input fields for name, sets, reps and weight
- [ ] there is a 'add' button to save the exercise
- [ ] there's a 'cancel' button to return to the 'plan summary' view
